export const FILTER_BY_GENRE_REQ = "FILTER_BY_GENRE_REQ";
export const FILTER_BY_RATE_REQ = "FILTER_BY_RATE_REQ";
export const FILTER_BY_DIRECTOR_REQ = "FILTER_BY_DIRECTOR_REQ";
export const FILTER_BY_GENRE_FAILED = "FILTER_BY_GENRE_FAILED";
export const FILTER_BY_RATE_FAILED = "FILTER_BY_RATE_FAILED";
export const FILTER_BY_DIRECTOR_FAILED = "FILTER_BY_DIRECTOR_FAILED";
