export const FILTER_BY_RATE_REQ = "FILTER_BY_RATE_REQ";

export const FILTER_BY_RATE_FAILED = "FILTER_BY_RATE_FAILED";

// by director

export const FILTER_BY_DIRECTOR_REQ = "FILTER_BY_DIRECTOR_REQ";
export const FILTER_BY_DIRECTOR_SUCCESS = "FILTER_BY_DIRECTOR_SUCCESS";
export const FILTER_BY_DIRECTOR_FAILED = "FILTER_BY_DIRECTOR_FAILED";

// by year

export const FILTER_BY_YEAR_REQ = "FILTER_BY_YEAR_REQ";
export const FILTER_BY_YEAR_FAILED = "FILTER_BY_YEAR_FAILED";
export const FILTER_BY_YEAR_SUCCESS = "FILTER_BY_YEAR_SUCCESS";

// by genre

export const FILTER_BY_GENRE_REQ = "FILTER_BY_GENRE_REQ";
export const FILTER_BY_GENRE_SUCCESS = "FILTER_BY_GENRE_SUCCESS";
export const FILTER_BY_GENRE_FAILED = "FILTER_BY_GENRE_FAILED";
