export const FETCH_LIKES_REQUEST = "FETCH_LIKES_REQUEST";
export const FETCH_LIKES_SUCCESS = "FETCH_LIKES_SUCCESS";
export const POST_LIKES_SUCCESS = "POST_LIKES_SUCCESS";
export const POST_LIKES_REQUEST = "POST_LIKES_REQUEST";
